channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.0.1
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.1.1
  - numpy==2.2.5
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.15.2
name: mlflow-env
